// <auto-generated />
using System;
using CangureraInteligente.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CangureraInteligente.Migrations
{
    [DbContext(typeof(CangureraDbContext))]
    [Migration("20260720154041_FixGpsCoordinatesPrecision")]
    partial class FixGpsCoordinatesPrecision
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CangureraInteligente.Models.CatTipoEvento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreEvento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Severidad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("NombreEvento")
                        .IsUnique();

                    b.ToTable("Cat_TiposEvento", "Operativo");
                });

            modelBuilder.Entity("CangureraInteligente.Models.Dispositivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<int>("OrganizacionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UltimaConexion")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MacAddress")
                        .IsUnique();

                    b.HasIndex("OrganizacionId");

                    b.ToTable("Dispositivos", "Operativo");
                });

            modelBuilder.Entity("CangureraInteligente.Models.EventoDetectado", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("DistanciaCm")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal?>("FuerzaImpactoG")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("Geo_Es_Estimado")
                        .HasColumnType("bit");

                    b.Property<bool?>("IrDerecho")
                        .HasColumnType("bit");

                    b.Property<bool?>("IrIzquierdo")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Latitud")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("Longitud")
                        .HasColumnType("decimal(9,6)");

                    b.Property<int>("RecorridoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimestampEvento")
                        .HasColumnType("datetime2");

                    b.Property<int>("TipoEventoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecorridoId");

                    b.HasIndex("TipoEventoId");

                    b.ToTable("Eventos_Detectados", "Operativo");
                });

            modelBuilder.Entity("CangureraInteligente.Models.Organizacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contacto_Principal")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Contrasena_Hash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email_Contacto")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Es_Interna")
                        .HasColumnType("bit");

                    b.Property<bool>("Estado_Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Organizaciones", "Operativo");
                });

            modelBuilder.Entity("CangureraInteligente.Models.Recorrido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DispositivoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DispositivoId");

                    b.ToTable("Recorridos", "Operativo");
                });

            modelBuilder.Entity("CangureraInteligente.Models.RecorridoCoordenada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Latitud")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitud")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<int>("RecorridoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecorridoId");

                    b.ToTable("RecorridoCoordenadas", "Operativo");
                });

            modelBuilder.Entity("CangureraInteligente.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contrasena_Hash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("Estado_Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("OrganizacionId")
                        .HasColumnType("int");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizacionId");

                    b.ToTable("Usuarios", "Operativo");
                });

            modelBuilder.Entity("CangureraInteligente.Models.Dispositivo", b =>
                {
                    b.HasOne("CangureraInteligente.Models.Organizacion", "Organizacion")
                        .WithMany("Dispositivos")
                        .HasForeignKey("OrganizacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organizacion");
                });

            modelBuilder.Entity("CangureraInteligente.Models.EventoDetectado", b =>
                {
                    b.HasOne("CangureraInteligente.Models.Recorrido", "Recorrido")
                        .WithMany("Eventos")
                        .HasForeignKey("RecorridoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CangureraInteligente.Models.CatTipoEvento", "TipoEvento")
                        .WithMany()
                        .HasForeignKey("TipoEventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recorrido");

                    b.Navigation("TipoEvento");
                });

            modelBuilder.Entity("CangureraInteligente.Models.Recorrido", b =>
                {
                    b.HasOne("CangureraInteligente.Models.Dispositivo", "Dispositivo")
                        .WithMany("Recorridos")
                        .HasForeignKey("DispositivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dispositivo");
                });

            modelBuilder.Entity("CangureraInteligente.Models.RecorridoCoordenada", b =>
                {
                    b.HasOne("CangureraInteligente.Models.Recorrido", "Recorrido")
                        .WithMany("Coordenadas")
                        .HasForeignKey("RecorridoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recorrido");
                });

            modelBuilder.Entity("CangureraInteligente.Models.Usuario", b =>
                {
                    b.HasOne("CangureraInteligente.Models.Organizacion", "Organizacion")
                        .WithMany("Usuarios")
                        .HasForeignKey("OrganizacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organizacion");
                });

            modelBuilder.Entity("CangureraInteligente.Models.Dispositivo", b =>
                {
                    b.Navigation("Recorridos");
                });

            modelBuilder.Entity("CangureraInteligente.Models.Organizacion", b =>
                {
                    b.Navigation("Dispositivos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("CangureraInteligente.Models.Recorrido", b =>
                {
                    b.Navigation("Coordenadas");

                    b.Navigation("Eventos");
                });
#pragma warning restore 612, 618
        }
    }
}
